//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoID { get; set; }
        public int FacturaID { get; set; }
        public decimal Monto { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string MetodoPago { get; set; }
    }
}
